---

apiVersion: v1
kind: Secret
metadata:
  name: cattle-credentials-cli
  namespace: cattle-system
type: Opaque
data:
  url: "aHR0cHM6Ly8xNzIuMjguMTI4LjEwCg=="
  token: "ajg3aHhmOXc5dGNibXRubHg4YmQ0OW1zOXZtcXh2cHh6NGIyZHpoNGt0aGc3Z3NibHNqZnI3Cg=="
