# Additional Trusted CAs.
# Enable this flag and add your CA certs as a secret named tls-ca-additional in the namespace.
# See README.md for details.
additionalTrustedCAs: false

addLocal: "auto"
# Add debug flag to Rancher server
debug: false

hostname: rancher1

### ingress ###
ingress:
  tls:
    source: secrets

privateCA: false

# Number of Rancher server replicas.
replicas: 1

tls: ingress
