---
<% 
require 'yaml'
hosts = YAML.load_file('vagrant/hosts.yml')
host_os = 'ubuntu-16.04'
%>
driver:
  name: vagrant
  username: vagrant
  sudo: true
  customize:
    cpus: 1
    memory: 2048
    cpuexecutioncap: 100
  synced_folders:
    - ["/tmp/shared", "/tmp/shared"]

transport:
  name: ssh

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  ansible_version: latest
  ansible_become: true
  ansible_host_key_checking: false
  ansible_inventory: vagrant/hosts.yml
  require_chef_for_busser: false

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-7

verifier:
  name: inspec

suites:
<% 
  hosts['all']['hosts'].each do |host, data| 
  ip1 = data['ansible_host']
  ip2 = data['rke_hack_ip']
%>
  - name: <%= host %>
    driver:
      vm_hostname: <%= host %>
      network:
      - ["private_network", {ip: <%= ip1  %>}]
      - ["private_network", {ip: <%= ip2  %>}]
    provisioner:
      ansible_limit: <%= host %>
      playbook: playbooks/setup.yml
    includes:
      - <%= host_os %>
    verifier:
      inspec_tests:
        - test/integration/default
<% end %>
