---
<% 
require 'yaml'
hosts = YAML.load_file('vagrant/hosts.yml')
%>
driver:
  name: vagrant
  username: vagrant
  sudo: true
  customize:
    cpus: 1
    memory: 2048
    cpuexecutioncap: 100
  synced_folders:
    - [".", "/vagrant"]

transport:
  name: ssh

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  ansible_version: latest
  ansible_become: true
  ansible_host_key_checking: false
  ansible_inventory: vagrant/hosts.yml
  extra_vars:
    ansible_ssh_pass: vagrant
  require_chef_for_busser: false
  roles_path: playbooks/roles

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-7

verifier:
  name: inspec

suites:
<% hosts['all']['hosts'].each do |host, data| %>
  - name: <%= host %>
    driver:
      vm_hostname: <%= host %>
      network:
      - ["private_network", {ip: <%= data['ansible_host']  %>}]
    provisioner:
      ansible_limit: <%= host %>
      playbook: vagrant/setup.yml
    includes:
      - <%= data['host_os'] %>
    verifier:
      inspec_tests:
        - test/integration/default
<% end %>
