- hosts: all

  vars:
    docker_package_state: absent

  roles:
    - geerlingguy.docker

  tasks:

    - name: Cleanup docker folders
      file: 
        path:  item }} 
        state: absent
      with_items:
        - /etc/docker
        - /var/lib/docker

