---
all:
  hosts:
    master1:
      ansible_host: 172.28.128.11
      access_ip: 172.28.128.11
      ip: 172.28.128.11
      host_os: ubuntu-18.04
    ## master2:
      ## ansible_host: 172.28.128.12
      ## host_os: ubuntu-18.04
    ## master3:
      ## ansible_host: 172.28.128.13
      ## host_os: ubuntu-18.04
    worker1:
      ansible_host: 172.28.128.21
      access_ip: 172.28.128.21
      ip: 172.28.128.21
      host_os: ubuntu-18.04
    worker2:
      ansible_host: 172.28.128.22
      access_ip: 172.28.128.22
      ip: 172.28.128.22
      host_os: ubuntu-18.04
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_user: vagrant
    ansible_become: true
    kubectl_localhost: true
    kubeconfig_localhost: true
  children:
    etcd:
      hosts:
        master1:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            master1:
        kube-node:
          hosts:
             worker1:
             worker2: 
    docker_engine:
      hosts:
        master1:
        worker1:
        worker2: 
    docker_swarm_manager:
      hosts:
        master1:
    docker_swarm_worker:
      hosts:
        worker1:
        worker2: 
