---
all:
  hosts:
    master1:
      ansible_host: 172.28.128.11
    worker1:
      ansible_host: 172.28.128.21
    worker2:
      ansible_host: 172.28.128.22
  vars:
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_become: true
  children:
    etcd:
      hosts:
        master1:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            master1:
        kube-node:
          hosts:
             worker1:
             worker2: 
    docker_engine:
      hosts:
        master1:
        worker1:
        worker2: 
    docker_swarm_manager:
      hosts:
        master1:
    docker_swarm_worker:
      hosts:
        worker1:
        worker2: 
