---
all:
  hosts:
    rancher1:
      ansible_host: 172.28.128.10
      rke_hack_ip: 172.28.128.110
    master1:
      ansible_host: 172.28.128.11
      rke_hack_ip: 172.28.128.111
    worker1:
      ansible_host: 172.28.128.21
      rke_hack_ip: 172.28.128.121
    worker2:
      ansible_host: 172.28.128.22
      rke_hack_ip: 172.28.128.122
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_user: vagrant
    ansible_ssh_pass: vagrant
    ansible_become: true
  children:
    etcd:
      hosts:
        master1:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            master1:
        kube-node:
          hosts:
             worker1:
             worker2: 
    docker_engine:
      hosts:
        master1:
        worker1:
        worker2: 
    docker_swarm_manager:
      hosts:
        master1:
    docker_swarm_worker:
      hosts:
        worker1:
        worker2: 
