---
all:
  hosts:
    master1:
      ansible_host: 172.28.128.11
      rke_hack_ip: 172.28.128.111
      host_os: ubuntu-18.04
    ## master2:
      ## ansible_host: 172.28.128.12
      ## rke_hack_ip: 172.28.128.112
      ## host_os: ubuntu-18.04
    worker1:
      ansible_host: 172.28.128.21
      rke_hack_ip: 172.28.128.121
      host_os: ubuntu-18.04
    worker2:
      ansible_host: 172.28.128.22
      rke_hack_ip: 172.28.128.122
      host_os: ubuntu-18.04
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_user: vagrant
    ##ansible_ssh_pass: vagrant
    ansible_become: true
  children:
    etcd:
      hosts:
        master1:
    k8s-cluster:
      children:
        kube-master:
          hosts:
            master1:
        kube-node:
          hosts:
             worker1:
             worker2: 
    docker_engine:
      hosts:
        master1:
        worker1:
        worker2: 
    docker_swarm_manager:
      hosts:
        master1:
    docker_swarm_worker:
      hosts:
        worker1:
        worker2: 
