- hosts: all

  vars:
    pip_install_packages:
      - name: docker
    docker_version: '17.03'
    docker_edition: 'ce'
    ## docker_package: "docker-{{ docker_edition }}={{ docker_version }}.*"
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Add ansible_user to group docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
