- hosts: all

  vars:

  roles:

  tasks:
    - name: Copy rootca crt to host
      copy:
        src: ../rancher/cacerts.pem
        dest: /usr/local/share/ca-certificates/cacerts.crt
        mode: 0644

    - name: Run update-ca-certificates
      command: update-ca-certificates

    - name: Add Rancher IP address to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*rancher.minikube.info$'
        line: "192.168.99.103 minikube.info rancher.minikube.info"
        state: present
